class ACE_ADDON(Medical_Treatment) {
    class Medication {
        // How much does the pain get reduced?
        painReduce = 0;
        // How much will the heart rate be increased when the HR is low (below 55)? {minIncrease, maxIncrease}
        hrIncreaseLow[] = {0, 0};    // _heartRate < 55
        hrIncreaseNormal[] = {0, 0}; // 55 <= _heartRate <= 110
        hrIncreaseHigh[] = {0, 0};   // 110 < _heartRate

        // How long until this medication has disappeared
        timeInSystem = 120;
        // How long until the maximum effect is reached
        timeTillMaxEffect = 30;
        // How many of this type of medication can be in the system before the patient overdoses?
        OD50 = -1;
        // The number of doses over maxDose where there is a chance to overdose.
        // Example with OD50 = 4 and maxDoseDeviation = 2: Dose 4: Safe | Dose 5 and 6: Possible overdose | Dose 7: Guaranteed overdose
        maxDoseDeviation = 2;
        // The dose of the medication, to allow for different dose amounts of the same medication
        dose = 1;
        // Function to execute upon overdose. Arguments passed to call back are 0: unit <OBJECT>, 1: medicationClassName <STRING>
        onOverDose = "";
        // The viscosity of a fluid is a measure of its resistance to gradual deformation by shear stress or tensile stress. For liquids, it corresponds to the informal concept of "thickness". This value will increase/decrease the viscoty of the blood with the percentage given. Where 100 = max. Using the minus will decrease viscosity
        viscosityChange = 0;
        // How much does the medication constrict/dilate the patient's blood vessels?
        alphaFactor = 0;
        // Max amount of pain the medication can remove
        maxRelief = 0;
        // Reduction of damage from wounds
        opioidRelief = 0;
        // How strong should opioid Respiratory Depression be be
        opioidDepression = 0;
        // How strong should opioid visuals be
        opioidEffect = 0;
        //multiplier to respiratory rate
        respiratoryRate = 0;
        //multiplier to contractility
        contractility = 0;
        //Is the medication dosaging based off of weight
        weightBased = 0;
        //what dose corresponds to a weight of 80kg
        weightDose = 20;
        //if weightDose isnt 20 (default), what is the upper and lower range of doses
        weightDoseMin = 10; //60kg
        weightDoseMax = 30; //100kg
        //maximum dose before medication effects are reduced
        maximumEffectiveDose = 40;
        //how far over max effective dose before it scales to 0
        maxOverEffective = 40;
        //multiplier to nausea
        nauseaMult = 0;
        //is this drug a sedation drug
        sedation = 0;
        paralysis = 0;
        bloodBased = 0;
        linear = 0;
        cnsSuppression = 0;
        LD50 = -1;
        chanceToOD = -1;
        //at what dose does this drug have therapeutic effects
        therapeutic = 15;

        class Epinephrine {};
        class Morphine {};
        class Adenosine {};
        class Atropine {};
        class TXAAuto {};
        class PhenylephrineAuto {};
        class Carbonate {
            painReduce = 0;
            hrIncreaseLow[] = {5, 10};
            hrIncreaseNormal[] = {10, 15};
            hrIncreaseHigh[] = {15, 20};
            timeInSystem = 30;
            timeTillMaxEffect = 2;
            dose = 10;
            viscosityChange = 0;
            OD50 = 60;
            LD50 = 240;
            chanceToOD = 5;
            maxDoseDeviation = 120;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 120;
            maxOverEffective = 20;
        };
        class CWMP {
            painReduce = 0.2;
            hrIncreaseLow[] = {0, 5};
            hrIncreaseNormal[] = {5, 10};
            hrIncreaseHigh[] = {5, 10};
            timeInSystem = 1200;
            timeTillMaxEffect = 45;
            dose = 10;
            viscosityChange = -5;
            maxRelief = 0.4;
            OD50 = 80;
            LD50 = 240;
            chanceToOD = -1;
            maxDoseDeviation = 120;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 120;
            maxOverEffective = 20;
        };
        class PainKillers {
            painReduce = 0.2;
            hrIncreaseLow[] = {0, 5};
            hrIncreaseNormal[] = {5, 10};
            hrIncreaseHigh[] = {5, 10};
            timeInSystem = 1200;
            timeTillMaxEffect = 45;
            dose = 10;
            viscosityChange = -5;
            maxRelief = 0.4;
            OD50 = 80;
            LD50 = 240;
            chanceToOD = -1;
            maxDoseDeviation = 120;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 120;
            maxOverEffective = 20;
        };
        class Pervitin {
            painReduce = 0.5;
            hrIncreaseLow[] = {15, 25};
            hrIncreaseNormal[] = {15, 30};
            hrIncreaseHigh[] = {15, 25};
            timeInSystem = 1200;
            timeTillMaxEffect = 5;
            dose = 10;
            viscosityChange = 5;
            opioidEffect = 0.2;
            nauseaMult = 0.2;
            OD50 = 30;
            LD50 = 60;
            chanceToOD = 5;
            maxDoseDeviation = 120;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 120;
        };
        class Caffeine {
            painReduce = 0;
            hrIncreaseLow[] = {0, 5};
            hrIncreaseNormal[] = {5, 10};
            hrIncreaseHigh[] = {5, 15};
            timeInSystem = 1800;
            timeTillMaxEffect = 5;
            dose = 10;
            viscosityChange = 0;
            respiratoryRate = 0.1;
            OD50 = 40;
            LD50 = 200;
            chanceToOD = 5;
            maxDoseDeviation = 120;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 120;
        };
        class BubbleWrap {
            painReduce = 0.05;
            hrIncreaseLow[] = {0, 0};
            hrIncreaseNormal[] = {0, 0};
            hrIncreaseHigh[] = {0, 0};
            timeInSystem = 300;
            timeTillMaxEffect = 5;
            dose = 1;
            viscosityChange = 0;
            OD50 = -1;
            LD50 = -1;
            chanceToOD = -1;
            maxDoseDeviation = 120;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 120;
        };
        class Penthrox {
            painReduce = 0.6;
            hrIncreaseLow[] = {-0, -5};
            hrIncreaseNormal[] = {-5, -10};
            hrIncreaseHigh[] = {-5, -15};
            timeInSystem = 2400;
            timeTillMaxEffect = 20;
            dose = 15;
            viscosityChange = 5;
            maxRelief = 0.6;
            bloodBased = 1;
            OD50 = 120;
            LD50 = 240;
            chanceToOD = 5;
            maxDoseDeviation = 120;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 120;
        };
        class syringe_TXA {
            painReduce = 0;
            hrIncreaseLow[] = {-2, 0};
            hrIncreaseNormal[] = {-3, -1};
            hrIncreaseHigh[] = {-4, -2};
            timeInSystem = 360;
            timeTillMaxEffect = 15;
            dose = 1;
            viscosityChange = 0;
            bloodBased = 1;
            OD50 = 40;
            LD50 = 100;
            chanceToOD = 5;
            maxDoseDeviation = 10;
            incompatibleMedication[] = {};
            onOverDose = "";
            therapeutic = 6;
        };
        class syringe_EACA {
            painReduce = 0;
            hrIncreaseLow[] = {-1, 0};
            hrIncreaseNormal[] = {-2, -1};
            hrIncreaseHigh[] = {-3, -1};
            timeInSystem = 360;
            timeTillMaxEffect = 25;
            dose = 1;
            viscosityChange = 0;
            bloodBased = 1;
            OD50 = 30;
            LD50 = 80;
            chanceToOD = 5;
            maxDoseDeviation = 10;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 20;
            therapeutic = 6;
        };
        class syringe_Epinephrine {
            painReduce = 0;
            hrIncreaseLow[] = {10, 18};
            hrIncreaseNormal[] = {10, 18};
            hrIncreaseHigh[] = {8, 15};
            timeInSystem = 120;
            timeTillMaxEffect = 5;
            dose = 1;
            alphaFactor = -0.08;
            contractility = 0.25;
            respiratoryRate = 0.12;
            OD50 = 90;
            LD50 = 150;
            chanceToOD = 5;
            maxDoseDeviation = 10;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
        };
        class syringe_Phenylephrine {
            painReduce = 0;
            hrIncreaseLow[] = {-5, 2};
            hrIncreaseNormal[] = {-8, 0};
            hrIncreaseHigh[] = {-10, -2};
            timeInSystem = 360;
            timeTillMaxEffect = 15;
            viscosityChange = 10;
            dose = 1;
            alphaFactor = -0.3;
            OD50 = 60;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 20;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
        };
        class syringe_Fentanyl {
            painReduce = 1;
            hrIncreaseLow[] = {-4, -7};
            hrIncreaseNormal[] = {-4, -10};
            hrIncreaseHigh[] = {-7, -12};
            timeInSystem = 7200;
            timeTillMaxEffect = 10;
            dose = 1;
            viscosityChange = -10;
            opioidRelief = 1.2;
            opioidEffect = 0.11;
            contractility = -0.1;
            nauseaMult = 0.5;
            bloodBased = 1;
            cnsSuppression = 0.3;
            OD50 = 30;
            LD50 = 60;
            chanceToOD = 5;
            maxDoseDeviation = 10;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
            weightBased = 1;
        };
        class syringe_Ketamine {
            painReduce = 0.8;
            hrIncreaseLow[] = {5, 10};
            hrIncreaseNormal[] = {5, 10};
            hrIncreaseHigh[] = {5, 10};
            timeInSystem = 3600;
            timeTillMaxEffect = 15;
            dose = 1;
            viscosityChange = 5;
            opioidEffect = 0.05;
            opioidDepression = 0.05;
            respiratoryRate = 0.07;
            contractility = 0.08;
            weightDose = 15;
            weightDoseMin = 10;
            weightDoseMax = 20;
            nauseaMult = 0.2;
            bloodBased = 1;
            OD50 = 60;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 20;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
            weightBased = 1;
        };
        class syringe_Nalbuphine {
            painReduce = 0.8;
            hrIncreaseLow[] = {-5, 0};
            hrIncreaseNormal[] = {-10, -5};
            hrIncreaseHigh[] = {-15, -5};
            timeInSystem = 5400;
            timeTillMaxEffect = 45;
            dose = 1;
            viscosityChange = -5;
            opioidRelief = 1.1;
            contractility = -0.1;
            weightDose = 20;
            nauseaMult = 0.3;
            bloodBased = 1;
            cnsSuppression = 0.15;
            OD50 = 60;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 20;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
            weightBased = 1;
            maxOverEffective = 1;
        };
        class syringe_Atropine {
            painReduce = 0;
            hrIncreaseLow[] = {8, 20};
            hrIncreaseNormal[] = {6, 16};
            hrIncreaseHigh[] = {3, 10};
            timeInSystem = 540;
            timeTillMaxEffect = 10;
            dose = 1;
            viscosityChange = 0;
            contractility = 0.1;
            OD50 = 50;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 30;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
        };
        class syringe_Amiodarone {
            painReduce = 0;
            hrIncreaseLow[] = {-2, 0};
            hrIncreaseNormal[] = {-5, -2};
            hrIncreaseHigh[] = {-8, -3};
            timeInSystem = 540;
            timeTillMaxEffect = 30;
            dose = 1;
            viscosityChange = 0;
            contractility = -0.2;
            bloodBased = 1;
            OD50 = 50;
            LD50 = 110;
            chanceToOD = 5;
            maxDoseDeviation = 10;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
        };
        class syringe_Lidocaine {
            painReduce = 0;
            hrIncreaseLow[] = {-1, 0};
            hrIncreaseNormal[] = {-2, -1};
            hrIncreaseHigh[] = {-3, -1};
            timeInSystem = 240;
            timeTillMaxEffect = 30;
            dose = 1;
            contractility = -0.1;
            OD50 = 60;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 30;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
        };
        class syringe_Etomidate {
            painReduce = 0.2;
            hrIncreaseLow[] = {0, -5};
            hrIncreaseNormal[] = {-5, -10};
            hrIncreaseHigh[] = {-10, -15};
            timeInSystem = 90;
            timeTillMaxEffect = 5;
            dose = 1;
            viscosityChange = 0;
            contractility = -0.05;
            weightDose = 20;
            bloodBased = 1;
            cnsSuppression = 0.1;
            OD50 = 60;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 20;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
            weightBased = 1;
            therapeutic = 16;
        };
        class syringe_Flumazenil {
            painReduce = 0;
            hrIncreaseLow[] = {0, 0};
            hrIncreaseNormal[] = {0, 0};
            hrIncreaseHigh[] = {0, 0};
            timeInSystem = 300;
            timeTillMaxEffect = 5;
            dose = 1;
            viscosityChange = 0;
            OD50 = 40;
            LD50 = 80;
            chanceToOD = 5;
            maxDoseDeviation = 20;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
            therapeutic = 16;
        };
        class syringe_Lorazepam {
            painReduce = 0;
            hrIncreaseLow[] = {-2, 2};
            hrIncreaseNormal[] = {-5, 0};
            hrIncreaseHigh[] = {-5, -2};
            timeInSystem = 3600;
            timeTillMaxEffect = 30;
            dose = 1;
            viscosityChange = -5;
            contractility = -0.1;
            weightDose = 20;
            cnsSuppression = 0.15;
            OD50 = 40;
            LD50 = 80;
            chanceToOD = 5;
            maxDoseDeviation = 20;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
            weightBased = 1;
            therapeutic = 16;
        };
        class syringe_Morphine {
            painReduce = 0.7;
            hrIncreaseLow[] = {-5, -10};
            hrIncreaseNormal[] = {-5, -15};
            hrIncreaseHigh[] = {-5, -15};
            timeInSystem = 5400;
            timeTillMaxEffect = 60;
            dose = 1;
            viscosityChange = -7;
            opioidRelief = 1.1;
            weightDose = 20;
            nauseaMult = 0.3;
            cnsSuppression = 0.2;
            OD50 = 60;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 30;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
            weightBased = 1;
        };
        class syringe_Adenosine {
            painReduce = 0;
            hrIncreaseLow[] = {-3, -10};
            hrIncreaseNormal[] = {-7, -15};
            hrIncreaseHigh[] = {-7, -20};
            timeInSystem = 60;
            timeTillMaxEffect = 2;
            dose = 1;
            viscosityChange = 0;
            OD50 = 60;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 30;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
        };
        class syringe_Doxapram {
            painReduce = 0;
            hrIncreaseLow[] = {3, 10};
            hrIncreaseNormal[] = {5, 10};
            hrIncreaseHigh[] = {5, 15};
            timeInSystem = 360;
            timeTillMaxEffect = 15;
            dose = 1; 
            respiratoryRate = 0.12;
            opioidDepression = -0.175;
            OD50 = 60;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 20;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
        };
        class syringe_Ondansetron {
            painReduce = 0.0;
            hrIncreaseLow[] = {0, 0};
            hrIncreaseNormal[] = {0, 0};
            hrIncreaseHigh[] = {0, 0};
            timeInSystem = 600;
            timeTillMaxEffect = 15;
            dose = 1;
            viscosityChange = 0;
            nauseaMult = -0.7;
            weightDose = 20;
            OD50 = 60;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 20;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
            weightBased = 1;
        };
        class syringe_Succinylcholine {
            painReduce = 0.0;
            hrIncreaseLow[] = {-5, 5};
            hrIncreaseNormal[] = {-5, 5};
            hrIncreaseHigh[] = {-10, 5};
            timeInSystem = 60;
            timeTillMaxEffect = 5;
            dose = 1;
            weightDose = 20;
            OD50 = 60;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 10;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
            weightBased = 1;
        };
        class syringe_Rocuronium {
            painReduce = 0.0;
            hrIncreaseLow[] = {0, 0};
            hrIncreaseNormal[] = {0, 0};
            hrIncreaseHigh[] = {0, 0};
            timeInSystem = 3600;
            timeTillMaxEffect = 15;
            dose = 1;
            weightDose = 20;
            OD50 = 60;
            LD50 = 110;
            chanceToOD = 5;
            maxDoseDeviation = 10;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
            weightBased = 1;
            therapeutic = 16;
        };
        class syringe_Sugammadex  {
            painReduce = 0.0;
            hrIncreaseLow[] = {0, 0};
            hrIncreaseNormal[] = {0, 0};
            hrIncreaseHigh[] = {0, 0};
            timeInSystem = 60;
            timeTillMaxEffect = 15;
            dose = 1;
            OD50 = 60;
            LD50 = 110;
            chanceToOD = 5;
            maxDoseDeviation = 10;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
            therapeutic = 16;
        };
        class syringe_Metoprolol  {
            painReduce = 0.0;
            hrIncreaseLow[] = {-4, -11};
            hrIncreaseNormal[] = {-8, -16};
            hrIncreaseHigh[] = {-8, -16};
            timeInSystem = 900;
            timeTillMaxEffect = 5;
            dose = 1;
            alphaFactor = -0.05;
            contractility = -0.15;
            OD50 = 50;
            LD50 = 100;
            chanceToOD = 5;
            maxDoseDeviation = 20;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
        };
        class syringe_Diazepam  {
            painReduce = 0;
            hrIncreaseLow[] = {-2, 0};
            hrIncreaseNormal[] = {-3, -5};
            hrIncreaseHigh[] = {-3, -5};
            timeInSystem = 5400;
            timeTillMaxEffect = 10;
            dose = 1; 
            cnsSuppression = 0.3;
            OD50 = 60;
            LD50 = 140;
            chanceToOD = 5;
            maxDoseDeviation = 20;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
        };
        class syringe_CalciumChloride {
            painReduce = 0;
            hrIncreaseLow[] = {1,5};
            hrIncreaseNormal[] = {1,5};
            hrIncreaseHigh[] = {0,3};
            timeInSystem = 60;
            timeTillMaxEffect = 5;
            contractility = 0.15;
            dose = 1;
            alphaFactor = -0.08;
            OD50 = 120;
            LD50 = 240;
            chanceToOD = 5;
            maxDoseDeviation = 120;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 120;
        };
        class syringe_CalciumGluconate {
            painReduce = 0;
            hrIncreaseLow[] = {1,5};
            hrIncreaseNormal[] = {1,5};
            hrIncreaseHigh[] = {0,3};
            contractility = 0.08;
            timeInSystem = 240;
            timeTillMaxEffect = 15;
            dose = 1;
            alphaFactor = -0.04;
            OD50 = 120;
            LD50 = 240;
            chanceToOD = 5;
            maxDoseDeviation = 120;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 120;
        };
        class syringe_Bicarbonate {
            painReduce = 0;
            hrIncreaseLow[]    = {2, 8};
            hrIncreaseNormal[] = {2, 8};
            hrIncreaseHigh[]   = {0, 5};
            timeInSystem = 120;
            timeTillMaxEffect = 10;
            dose = 1;
            alphaFactor = 0.06;
            OD50 = 120;
            LD50 = 240;
            chanceToOD = 5;
            maxDoseDeviation = 120;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 120;
        };
        class syringe_Alteplase {
            painReduce = 0;
            hrIncreaseLow[] = {-2, 0};
            hrIncreaseNormal[] = {-3, -1};
            hrIncreaseHigh[] = {-5, -2};
            timeInSystem = 180;
            timeTillMaxEffect = 30;
            dose = 1;
            OD50 = 40;
            LD50 = 240;
            maxDoseDeviation = 10;
            incompatibleMedication[] = {};
            viscosityChange = 0;
            maximumEffectiveDose = 30;
        };
        class syringe_Norepinephrine {
            painReduce = 0;
            hrIncreaseLow[] = {1, 3};
            hrIncreaseNormal[] = {1, 3};
            hrIncreaseHigh[] = {1, 4};
            timeInSystem = 3;
            timeTillMaxEffect = 1;
            dose = 1;
            volume = 100;
            rateCoef = 1.4;
            alphaFactor = -0.075;
            viscosityChange = 4;
            OD50 = 40;
            LD50 = 90;
            chanceToOD = 5;
            maxDoseDeviation = 10;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
        };
        class syringe_Nitroglycerin {
            painReduce = 0;
            hrIncreaseLow[] = {1, 3};
            hrIncreaseNormal[] = {1, 3};
            hrIncreaseHigh[] = {1, 4};
            timeInSystem = 3;
            timeTillMaxEffect = 1;
            dose = 1;
            volume = 100;
            rateCoef = 1.4;
            alphaFactor = 0.05;
            viscosityChange = -2;
            contractility = -0.05;
            OD50 = 60;
            LD50 = 120;
            chanceToOD = 5;
            maxDoseDeviation = 30;
            incompatibleMedication[] = {};
            onOverDose = "";
            maximumEffectiveDose = 30;
        };
    };
};